### ISSUE TITLE
Problem with height in menus

### ISSUE THREAD

**Issue by DrW3b** [overdodactyl/ShadowFox#107]
Hi, I'm using your updated files and I have this problem in Win 7

![Ss1](https://i.imgur.com/82gLuIB.png)
![Ss2](https://i.imgur.com/9d9BKeE.png)
![Ss3](https://i.imgur.com/8mYa2FM.png)

**Comment by stonecrusher** [comment]
Looks well here:
![neue bitmap](https://user-images.githubusercontent.com/1388389/38238717-1106aeca-372b-11e8-9f66-249fe412fd1c.png)

Win 7x32
FF 59.0.2 (32-bit)
latest ShadowFox

**Comment by martyschaer** [comment]
This is also an Issue on Arch Linux, running i3wm. The menus look squashed compared with default.

**Comment by overdodactyl** [comment]
Thanks @martyschaer, I'll see if I can get hold of a Linux user and have them look into it.

**Comment by overdodactyl** [comment]
Thanks for letting me know @Stonebuilt - keep me updated if you find anything

**Comment by qazip** [comment]
I am also using linux with i3wm and this is the one thing that's bugging me: The height of the items in the context menu.

**Comment by slapjd** [comment]
Using windows 10 on latest firefox, this is also bugging me on the right click context menu. I found that adding this to the userchrome customization solves the problem for me, or at least works around it

```css
#PlacesToolbar menupopup > menu,
#PlacesToolbar menupopup > menuitem,
menupopup#contentAreaContextMenu > menu,
menupopup#contentAreaContextMenu > menuitem,
menupopup#placesContext menuitem,
menupopup#tabContextMenu > menu,
menupopup#tabContextMenu > menuitem,
menupopup#tabContextMenu menupopup > menu,
menupopup#tabContextMenu menupopup > menuitem,
menupopup#toolbar-context-menu > menuitem {
  font-size: 1.167em!important;
}
#PlacesToolbar menupopup menupopup > menu,
#PlacesToolbar menupopup menupopup > menuitem,
menupopup#contentAreaContextMenu menupopup > menu,
menupopup#contentAreaContextMenu menupopup > menuitem,
menupopup#tabContextMenu menupopup > menu,
menupopup#tabContextMenu menupopup > menuitem,
menupopup.textbox-contextmenu > menuitem {
  font-size: 1em!important
}
toolbaritem#menubar-items menupopup > menu,
toolbaritem#menubar-items menupopup > menuitem {
  font-size: 1.167em!important
}
toolbaritem#menubar-items menupopup menupopup > menu,
toolbaritem#menubar-items menupopup menupopup > menuitem {
  font-size: 1em!important
}
```

This was pulled and then stripped down from the old userchrome windows file that used to be in this repo. I figured it might help solve the issue

**Comment by zyvy11** [comment]
instead of:
font-size: 1.167em!important; 
you can use margin or padding 

this is what i did:

#PlacesToolbar menupopup > menu,
#PlacesToolbar menupopup > menuitem,
menupopup#contentAreaContextMenu > menu,
menupopup#contentAreaContextMenu > menuitem,
menupopup#placesContext menuitem,
menupopup#tabContextMenu > menu,
menupopup#tabContextMenu > menuitem,
menupopup#tabContextMenu menupopup > menu,
menupopup#tabContextMenu menupopup > menuitem,
menupopup#toolbar-context-menu > menuitem {
  margin-top: 3px!important;
  margin-bottom: 3px!important;
}
#PlacesToolbar menupopup menupopup > menu,
#PlacesToolbar menupopup menupopup > menuitem,
menupopup#contentAreaContextMenu menupopup > menu,
menupopup#contentAreaContextMenu menupopup > menuitem,
menupopup#tabContextMenu menupopup > menu,
menupopup#tabContextMenu menupopup > menuitem,
menupopup.textbox-contextmenu > menuitem {
    margin-top: 3px!important;
  margin-bottom: 3px!important;
}
toolbaritem#menubar-items menupopup > menu,
toolbaritem#menubar-items menupopup > menuitem {
    margin-top: 3px!important;
  margin-bottom: 3px!important;
}
toolbaritem#menubar-items menupopup menupopup > menu,
toolbaritem#menubar-items menupopup menupopup > menuitem {
    margin-top: 3px!important;
  margin-bottom: 3px!important;
}

**Comment by slapjd** [comment]
Screenshots for reference:
Original userchrome fix:
![olduserchromemenu](https://user-images.githubusercontent.com/19635889/41363821-d7768ede-6f2c-11e8-9683-abb78b6fd6f4.PNG)

@zyvy11's userchrome fix
![newuserchromemenu](https://user-images.githubusercontent.com/19635889/41363896-ff518896-6f2c-11e8-838a-e3c59ce5a61f.PNG)

No shadowfox:
![nouserchromemenu](https://user-images.githubusercontent.com/19635889/41363927-15346804-6f2d-11e8-89da-dd7629dff178.PNG)

Default shadowfox:
![defaultuserchromemenu](https://user-images.githubusercontent.com/19635889/41363950-23f51708-6f2d-11e8-947d-51440d970ec4.PNG)

At least, this is how they appear on my machine: windows 10 and firefox 60.0.2 64-bit

**Comment by zyvy11** [comment]
all changes that i put ,

userChrome.css
```css
/* Toolbar bookmarks */
#PersonalToolbar{
color:#afafaf !important;
}

/* Prevent flash white page when open new tab  */
@-moz-document url("chrome://browser/content/browser.xul") {
  tabbrowser tabpanels {
    background-color: #000 !important;
  }
}

/*Prevent flash white page when open new tab */
browser[type="content-primary"], tabbrowser tabpanels, #appcontent > #content{
 background-color: #000 !important; }


/* selected tab */
.tabbrowser-tab[visuallyselected="true"] {
    color:#afafaf !important;
}

/* not selected tab */
.tabbrowser-tab:not([visuallyselected="true"]) {
    font-style: italic !important;
    color:#afafaf !important;
}

/**MENU MARGIN, RIGHT CLICK MOUSE MENU MARGIN: FILE, EDIT, VIEW, HISTORY...**/
#PlacesToolbar menupopup > menu,
#PlacesToolbar menupopup > menuitem,
menupopup#contentAreaContextMenu > menu,
menupopup#contentAreaContextMenu > menuitem,
menupopup#placesContext menuitem,
menupopup#tabContextMenu > menu,
menupopup#tabContextMenu > menuitem,
menupopup#tabContextMenu menupopup > menu,
menupopup#tabContextMenu menupopup > menuitem,
menupopup#toolbar-context-menu > menuitem {
  margin-top: 3px!important;
  margin-bottom: 3px!important;
}
#PlacesToolbar menupopup menupopup > menu,
#PlacesToolbar menupopup menupopup > menuitem,
menupopup#contentAreaContextMenu menupopup > menu,
menupopup#contentAreaContextMenu menupopup > menuitem,
menupopup#tabContextMenu menupopup > menu,
menupopup#tabContextMenu menupopup > menuitem,
menupopup.textbox-contextmenu > menuitem {
    margin-top: 3px!important;
  margin-bottom: 3px!important;
}
toolbaritem#menubar-items menupopup > menu,
toolbaritem#menubar-items menupopup > menuitem {
    margin-top: 3px!important;
  margin-bottom: 3px!important;
}
toolbaritem#menubar-items menupopup menupopup > menu,
toolbaritem#menubar-items menupopup menupopup > menuitem {
    margin-top: 3px!important;
  margin-bottom: 3px!important;
}


/**BROWSER TOP MENU COLOR FOR INACTIVE ITEMS: FILE, EDIT, VIEW, HISTORY...**/
toolbaritem#menubar-items menupopup > menu[disabled=true],
toolbaritem#menubar-items menupopup > menuitem[disabled=true] {
  color:#434343 !important;
}

/*GREYED OUT/INACTIVE MENU BACKGROUND COLOR right click menu*/
menu:hover[disabled=true],
menuitem:hover[disabled=true]{
  color: #434343 !important;
  background-color: #202020!important
}
/*right mouse button menu left and right arrows*/
#context-navigation menuitem:hover[disabled=true] { 
}
/**BACKGROUND COLOR ON HOVER MENU - red**/
menuitem[_moz-menuactive=true],
menupopup menu[_moz-menuactive=true] {
  color: #c0c0c0 !important;/*right mouse button menu icons top right corner*/
  background-color: #330000 !important
}

menu.subviewbutton > .menu-right {
  fill: #000!important
}
.menu-right {
  filter: invert(95%)!important
}
#context-navigation menuitem,
.panel-arrowcontent {
}
#context-navigation menuitem:hover {
}

menuitem,
menupopup menu {
  -moz-appearance: none!important;
}

menupopup menuseparator {
}
```


userContent.css

```css

/* Prevent flash white page when open new tab  */
@-moz-document url("about:newtab") {
  body {
    background-color: #000 !important;
  }
}

/* Prevent flash white page when open new tab  */

@-moz-document regexp("^about:(?!reader).*"), url(https://www.mozilla.org/credits/) { 

 html:not(#ublock0-epicker), html:not(#ublock0-epicker) body, #newtab-customize-overlay {
  background: var(--tone-9) !important;
 }  
}

```

and it looks like 

top menu:

![Image of Yaktocat](https://imgur.com/Tau1XKK.jpg)

mouse right click:

![Image of Yaktocat](https://imgur.com/0KAM5pf.jpg)


ps:
separators are part of windows theme call:
Dark Agility 
downloaded from deviant art
