### ISSUE TITLE
Generic css for addon options

### ISSUE THREAD

**Issue by stonecrusher** [overdodactyl/ShadowFox#110]
In `about:addons` the options of certain extensions have black font-colour on grey background. Very poor contrast.

# tl;dr
If the background is changed to dark, also change the font colour to light! Is that possible?
I guess it's an iframe or specifity problem?

# Longread if not possible:

Now the approach to make a unique style for every addon out there is impossible to ever finish. Of course it makes sense for the most used addons. But sometimes I just want to test some unknown ones for some days or don't want to open an issue for every little extension I have.

There are three possibilities I came up with:
1. Don't touch the moz-extension options iframe at all (so it will be an ugly white block, but better than unusuable with dark background)
2. Make a generic style which will target all `@-moz-document url-prefix("moz-extension://") { }` and will be overwritten by the specific styles you made. This might also break certain options pages and needs the possibility to define exlusions, which is only possible by regex and overcomplicates it
3. Make a generic style which will target only UUIDs the user specified manually

So it could look something like this at the end:
```CSS
@-moz-document url-prefix("moz-extension://extension1_UUID/"),
url-prefix("moz-extension://extension2_UUID/"),
url-prefix("moz-extension://extension3_UUID/"),
url-prefix("moz-extension://extension4_UUID/")  {
    body,
    body * {
        background-color: var(--dark-1) !important;
        color: var(--light-1) !important;
    }
    button, label, texarea, form, whateverspecialgenericelement {
      background-color: var(--light-2) !important;
      color: var(--dark-1) !important;
    }
}
```

p.s.: Extensions whose options open in their own tab are not affected by faulty dark background (and shouldn't be affected by the generic style).

Some screenshots:
![1](https://user-images.githubusercontent.com/1388389/38449046-b756645a-3a0a-11e8-8219-07a6f0489711.PNG)
![2](https://user-images.githubusercontent.com/1388389/38449047-b7733562-3a0a-11e8-8198-bbc2b5d6c793.PNG)
![3](https://user-images.githubusercontent.com/1388389/38449048-b7897084-3a0a-11e8-8d34-55d432513f27.PNG)
![4](https://user-images.githubusercontent.com/1388389/38449049-b7a30756-3a0a-11e8-9ee1-d47d687257a7.PNG)
![5](https://user-images.githubusercontent.com/1388389/38449050-b7bbcc8c-3a0a-11e8-91ae-6ff22d34f0c7.PNG)
![6](https://user-images.githubusercontent.com/1388389/38449051-b7d6818a-3a0a-11e8-9e5e-3be58e630afa.PNG)

**Comment by overdodactyl** [comment]
After doing a little testing, I think option 2 (generic styling) might be a really good way to go.  The following code works for all but one extension I have that has options in the `about:addons` section:

```css
@-moz-document regexp("^moz.*(options)\.html$") {
  body * {
      color: var(--in-content-page-color) !important;
  }
  * {
    border-color: var(--in-content-box-border-color)!important;
    text-shadow: none!important
  }
  select,
  select * {
    color: black !important;
  }
  a {
    color: var(--in-content-link-color) !important;
  }
  textarea,
  input[type="input"],
  input[type="text"],
  input[type="number"],
  input[type="url"] {
    -moz-appearance: none!important;
    background: var(--tone-6)!important;
    color: var(--tone-4)!important;
    border: 1px solid!important;
    border-color: var(--in-content-box-border-color)!important;
    padding: 5px 5px 5px 5px !important;
    margin-left: 3px !important;
  }
  button,
  input[type="submit"] {
    -moz-appearance: none!important;
    background-image: none!important;
    background-color: var(--in-content-page-background)!important;
    color: var(--in-content-page-color)!important;
    border: 1px solid!important;
    border-color: var(--in-content-box-border-color)!important;
    border-radius: 3px!important
  }
  button:hover,
  input[type="submit"]:hover {
    background-color: var(--in-content-box-background-hover)!important
  }
}
```

Using this would also cut back a large amount of redundant code in the `webextension-tweaks` directory as well.

**Comment by stonecrusher** [comment]
Oh no, my last post is gone somehow.

The short version: I don't know how to inspect that options iframe. Just doesn't work here :-/
I downloaded and unpacked some extensions' .xpi to look at the code and came up with some changes that make it work for most of my extensions. Still not perfect, but conveniant on a wide scale.

If we investigate and develop it a bit further imho it's definitely worth merging into the project.

```CSS
@-moz-document regexp("^moz-extension:\\/\\/.*(options|preferences|index|settings)\\.html$") {
  * {
    color: var(--in-content-page-color) !important;
    background-color: var(--in-content-page-background)!important;
    border-color: var(--in-content-box-border-color)!important;
    text-shadow: none!important
  }
  select,
  select * {
    color: black !important;
  }
  a {
    color: var(--in-content-link-color) !important;
  }
  h1, h2, h3, h4, h5, h6 {
    color: var(--in-content-category-text-selected)!important
  }
  fieldset {
    border: 2px solid!important;
    border-color: var(--in-content-box-border-color)!important
  }
  input  {
    background: var(--in-content-box-background)!important;
    color: var(--in-content-page-color)!important;
  }
  
  textarea,
  input[type="input"],
  input[type="text"],
  input[type="number"],
  input[type="url"]  {
    -moz-appearance: none!important;
    background: var(--in-content-box-background)!important;
    color: var(--in-content-page-color)!important;
    border: 1px solid!important;
    border-color: var(--in-content-box-border-color)!important;
    margin-left: 3px !important;
    padding-left: 3px !important;
  }
  textarea {
    padding: 5px 5px 5px 5px !important;
  }
  button,
  input[type="submit"] {
    -moz-appearance: none!important;
    background-image: none!important;
    background-color: var(--in-content-page-background)!important;
    color: var(--in-content-page-color)!important;
    border: 1px solid!important;
    border-color: var(--in-content-box-border-color)!important;
    border-radius: 3px!important
  }
  button:hover,
  input[type="submit"]:hover {
    background-color: var(--in-content-box-background-hover)!important
  }
}
```

**Comment by overdodactyl** [comment]
>I don't know how to inspect that options iframe. Just doesn't work here :-/

Easiest way is to go to `about:debugging#addons`, and click "Debug" for whatever extension you want to inspect - this will bring up the Browser Toolbox.  You can then choose what frame you want to inspect using the button in the top right (rectangle with two squares below):

![iframes](https://user-images.githubusercontent.com/33071129/38461915-e3c604c0-3acb-11e8-9dfe-99ee294b65f3.png)

This is also the easiest way I've found to inspect extension popups as well.  

The biggest issue I'm seeing is that there's no standard when it comes to the name of html pages.  Most seem to end in `options.html` for the settings in `about:addons`, but there are certainly others (namely those you pointed out - `settings`, `index`, `preferences`).  Those later ones seem to be more frequently used for settings pages that are outside of `about:addons`, however.  When that's the case, the generic styling can cause quite a few problems.  Since there's no definitive standard (in some cases, `options.html` is also used for external settings pages), I'm wondering if it would be better to actually use the third option you suggested.  

Doing so would still cut back on redundant code and it would make it easier for users to make quick fixes, but it would prevent the generic styling from creating even more problems.  

Thoughts?

**Comment by stonecrusher** [comment]
Aah, good old debugging. I never think about it. Should have known. Works, thanks!

> The biggest issue I'm seeing is that there's no standard when it comes to the name of html pages

Yes but I didn't see many more out there than the ones I listed. Do we even need to specify them?

>  used for settings pages that are outside of about:addons

Yeah but those should be styled too, no? [Example addon with external page](https://addons.mozilla.org/firefox/addon/imagus/)

So target everything but just not the popups because they are most likely to break? Are they really? Of course a complicated one like uBO will require special treatment.

Another possibility is to provide and activate generic styling (most comfortable - would be suggestion number 2) but also give examples for exclusions so that users can easily do that by themselves. In my experience RegEx knowledge is not very common among people who know CSS.

I vote for us doing more testing before going live and providing a regex like
```CSS
/* Exclude extensions from being styled by adding their UUID in the given scheme */
@-moz-document regexp("moz-extension:\/\/(?!moz-extension:\/\/(?!UUIDexmpl-1111-1111-1234-012345678910|UUIDexmpl-2222-2222-1234-012345678910|UUIDexmpl-3333-3333-1234-012345678910)\/.*)\/.*")
```

**Comment by overdodactyl** [comment]
>Yes but I didn't see many more out there than the ones I listed. Do we even need to specify them?

I think we do.  Painting with too broad of a stroke is only going to cause a lot more problems I think.  If we just start with `moz-extension`, then everything will be styled - `about:addons`, popups, settings pages, etc.  I currently don't have the time or help to make sure every extension is properly styled.  Using things like:

```css
* {
    color: var(--in-content-page-color) !important;
    background-color: var(--in-content-page-background)!important;
    border-color: var(--in-content-box-border-color)!important;
    text-shadow: none!important
  }
``` 

is going to break a lot of extensions.  Generally speaking, I think it's best for people to opt-in to having webextensions (settings pages and popups) styled rather than having to opt out.  If people download ShadowFox and see several extensions are broken, I think their first reaction will be to uninstall it, not find out how to create exceptions.  

>Yeah but those should be styled too, no?

Ideally, yes.  But again it's a matter of me not being able to maintain styling for a large number of extensions.  Keeping up with just the ones I personally use is already a decent amount of work.  

>So target everything but just not the popups because they are most likely to break? Are they really?

Both popups and external settings pages are much more likely to break with generic styling (simply because they have more involved with them than a little text and entry boxes).

>I vote for us doing more testing before going live

Definitely agree there :)

**Comment by stonecrusher** [comment]
>  Painting with too broad of a stroke is only going to cause a lot more problems I think. 

In general, yes. Although I thought all those things should be styled. So let's make it specific.

>  If people download ShadowFox and see several extensions are broken

Unfortunately that's the case at the moment and was the reason why I opened this issue. Just making the background dark doesn't work. Either don't touch moz-extension urls at all by default or make a general style and try to target as many extensions (options pages) as possible. Just overriding everything works pretty well here.

> I think their first reaction will be to uninstall it, not find out how to create exceptions.

Which speaks for solution number three: Opt-in for a generic style and the already existing specific ones.

I'm here to test and do my best with CSS. Currently I have 20 extensions active but will make another profile containing the most popular ones.
With the current setup of the generic style it is definitely an improvement for me. Even if there are still some things which don't look very well, at least I can read everything and use it.

Don't know if I have time tonight, but I can start a list of extensions and compare if their options pages work well.

**Comment by overdodactyl** [comment]
Wow, thank you for all this work! Sorry I didn't have time to look at it yet, but I'm about to dive into a bit more.

>You can't distinguish between internal and external (opened in new tab) options?

I don't believe so, no.  The only thing I was seeing was that *most* addons that had preferences in `about:addons` utilized `options.html`, but that wasn't always the case.

>Without using the specific style for e.g. Smart HTTPS, why does it have a dark background colour?

It's coming from the variable `--in-content-page-background`, which I redefined from the FF default in `color_variables.css`

>Maybe you could help with a selector to change the top text of a dropdown? 

Could you possible upload a screenshot or direct me to where I could see that problem?

**Comment by stonecrusher** [comment]
> Sorry I didn't have time to look at it yet, but I'm about to dive into a bit more.

Don't worry, take your time. I'm happy you like my suggestions.

> > You can't distinguish between internal and external (opened in new tab) options?

> I don't believe so, no. The only thing I was seeing was that most addons that had preferences in about:addons utilized options.html, but that wasn't always the case.

Yeah that's what I feared. Distiguishing just by url is proven to not work, they are arbitrary. Like Adblock Plus has an external `options.html` without being in any subfolder. But it's not so important as we however now try to darken everything.

> >   Without using the specific style for e.g. Smart HTTPS, why does it have a dark background colour?

> It's coming from the variable --in-content-page-background, which I redefined from the FF default in color_variables.css

So that's the culprit for extensions options to be unreadable in default SF settings. If geneneric.css won't be activated by default, we should find a workaround to keep the white background in extensions.

> Could you possible upload a screenshot or direct me to where I could see that problem?

Using [generic.css](https://pastebin.com/rnU0rwmD) with SF default settings, open the options for [Google Translator Extension](https://addons.mozilla.org/firefox/addon/google-translator-for-firefox/). The dropdown for language setting is unreadable. You can see a screenshot of that in my [results sheet](https://docs.google.com/spreadsheets/d/1uysYG7FKTnJ_qlIEHSm4I1QkYxuD93Uy8Uqb2bs-wtI/edit?usp=sharing). Same for [Video Blocker](https://addons.mozilla.org/firefox/addon/video-blocker/)

**Comment by overdodactyl** [comment]
Do you use mac, linux, or windows?

**Comment by stonecrusher** [comment]
Windows 8.1
Windows 7 in VM
Linux MINT in VM
I usually test with 8.1 because it's most similar to Windows 10 which is the most used OS

**Comment by overdodactyl** [comment]
So it hasn't been implemented in the Windows updater script yet (I don't have Windows, so I haven't been able to do it myself), but the mac and linux ones have a new-ish feature that can automatically find the UUID's of extensions.  

This could be a helpful way to "force" fixes onto webextensions that have problems.  Just something to consider in the mix of what to do with the generic styling.

The following makes the background white for webextensions prefs in `about:addons`:


```css
#addon-options {
    background-color: white !important;
}
```
