### ISSUE TITLE
findbar (ctrl f) not properly styled.

### ISSUE THREAD

**Issue by HRussell63250** [overdodactyl/ShadowFox#122]
If the default dark theme is disabled in favour of an image theme (installed from addons), findbar is not styled.
![image](https://user-images.githubusercontent.com/22746105/38747994-9af3ce1c-3f44-11e8-9993-0f1df4ff9041.png)

**Comment by overdodactyl** [comment]
Hmm, interesting.  This repo has been designed with the intent to supplement the dark theme as opposed to entirely re-create one.  I imagine if you disable the dark theme, there will be a few other quirks you encounter. If you want to make it dark, you could add something like the following to your`userChrome_customization.css` file:

```css
findbar {
  background-color: var(--in-content-category-header-background) !important;
}

.browserContainer > findbar .findbar-find-status, 
.browserContainer > findbar .found-matches, 
.browserContainer > findbar .findbar-button {
    color: var(--in-content-page-color) !important;
}

.findbar-closebutton.close-icon {
  fill: var(--in-content-page-color) !important;
}
```
If you want to keep it light, use something to the effect of:

```css
.findbar-textbox:not([status=notfound]) {
  background-color: -moz-Field !important;
  color: -moz-FieldText !important;
  border-color: rgba(0,0,0,.35) !important;
}

.findbar-find-next,
.findbar-find-previous {
  fill: black !important
}
```
