### ISSUE TITLE
Change for Firefox 61 beta + 1 other

### ISSUE THREAD

**Issue by loopy750** [overdodactyl/ShadowFox#143]
Changed in Firefox 61, for the bottom corner status panel, **_status_panel.css_**

Replace

```css
statuspanel .statuspanel-label {
```
with
```css
statuspanel .statuspanel-label, #statuspanel #statuspanel-label {
```

&

Drop down menu, **_context_menus.css_**

Go to http://www.overclock.net/forum/index.php , in the drop down menu, some items are white text with white background.

Can be fixed with

Replace

```css
menuitem,
menupopup menu {
  -moz-appearance: none!important;
  color: var(--in-content-selected-text)!important
}
```

with

```css
menuitem,
menupopup menu {
  -moz-appearance: none!important;
  color: var(--in-content-selected-text)!important;
  background: var(--in-content-box-background)!important;
}
```
