### ISSUE TITLE
ask. Hamburger menu color

### ISSUE THREAD

**Issue by johndoe71rus** [overdodactyl/ShadowFox#174]
Can you tell how to change the highlight color in the hamburger menu?
https://i.imgur.com/g7ZhXvz.png 
thanks.

**Comment by overdodactyl** [comment]
The following should do the trick:

```css
#appMenu-mainView toolbarbutton:hover {background-color: red !important;}
```
