### ISSUE TITLE
Add documentation for color variables

### ISSUE THREAD

**Issue by overdodactyl** [overdodactyl/ShadowFox#197]
Add documentation to the wiki for what each color variable alters.

This should make it easier for users to customize Firefox to a greater extent.

**Comment by arvenil** [comment]
If I would like to make New Tab background completely black which variable I should change?

**Comment by overdodactyl** [comment]
If you want to change the background of all ShadowFox styled pages (including ones like `about:preferences` and `about:addons`), you can adding the following to the `colorOverrides.css` file:

```css
--in-content-page-background: black !important;
```

If you want it to apply only on specific ones, you could add something like the following to `userContent_customization.css`:

```css
@-moz-document url(about:newtab), url(about:home), url("about:blank") {
     :root {
       --in-content-page-background: black !important;
     }
 }
```
