### ISSUE TITLE
Windows 7 Aero Glas

### ISSUE THREAD

**Issue by Feky** [overdodactyl/ShadowFox#203]
On Windows 7 when I use this theme it removes Aero effect. As you can see this is default dark theme on Windows 7

![firefox_default_dark_theme_on](https://user-images.githubusercontent.com/3746977/46636199-73313c80-cb57-11e8-8087-9eb84b76bc43.png)

And this is after applying shadowfox. It ads this black bar thing and it looks ugly.

![shadowfox_on_firefox](https://user-images.githubusercontent.com/3746977/46636220-8a702a00-cb57-11e8-8d0f-78496bf7ef9f.png)

Is it possible to remove it and keep Areo instead of this? It would look much better on Windows 7?

![shadowfox_on_firefox_pls_aero](https://user-images.githubusercontent.com/3746977/46636259-ad024300-cb57-11e8-9257-2b2751ddc2e0.png)

**Comment by overdodactyl** [comment]
I think this is due to the change made in #198.

I don't have Windows to test on, but the code causing this is the following:

```css
@-moz-document url-prefix(chrome://) {
  @media screen and (-moz-os-version:windows-win7) {
    window {
      background-color: var(--tone-9)!important;
      color: var(--in-content-page-color)!important
    }
  }
}
```

You could try adding an override in `userChrome_customization.css` and making the background-color `none` or `transparent` to see if that fixes it.

**Comment by Feky** [comment]
I'm not CSS master I did try and didn't work. Can you paste script with "none" color? Maybe I was doing wrong!

**Comment by overdodactyl** [comment]
```css
@-moz-document url-prefix(chrome://) {
  @media screen and (-moz-os-version:windows-win7) {
    window {
      background-color: none !important;
    }
  }
}
```

You could try replacing the word `none` with `transparent` as well.  After you add that to the `userChrome_customization.css`, make sure you re-run the updater script and restart Firefox.
