### ISSUE TITLE
XenForo Editor boxes are broken.

### ISSUE THREAD

**Issue by thakyZ** [overdodactyl/ShadowFox#227]
Firefox Stable 64.0 64-bit
Windows 7 (Have tested on Windows 10 too)

There is an issue with the Chucklefish Forums editor boxes, this seems to be the case for all XenForo sites.

Basically, go to a XenForo based forums, and hit reply to a topic or sumbit a new topic, and you can see the Message box seems to have a back background with black text.

![image](https://user-images.githubusercontent.com/950594/50046929-ef1c9900-0060-11e9-81e2-ed469b9033e6.png)

**Comment by thakyZ** [comment]
Ok I just figured out how to fix it.   
On line 3355 of the userContent.css (mine is modified so I am not sure if it's the same default), in the section titled "Dark 'About' Pages" change both parameters on the @-moz-document from url to domain. I have seen nothing wrong with the other pages and it seems to work just fine,

Example:
```css
/* ##### DARK 'ABOUT' PAGES ##################### */
@-moz-document domain('about:blank'), domain('about:newtab') {
	body {
		background-color: #383838 !important;
	}
}
```
