### ISSUE TITLE
Tabs Bar Color

### ISSUE THREAD

**Issue by GTK66** [overdodactyl/ShadowFox#233]
In Firefox 65 The Tabs Bar takes on the color that is set in windows 10.. In order to make it dark you either have to change the color settings in Windows 10 or leave out the check mark in Windows 10 Colors in Title Bars and Windows borders as shown in the image below. This will make the Tabs bar dark again, but it messes up Windows 10's Programs. If I leave the the check mark out, all programs in Windows 10 will have a bright tool bar. I use ShadowFox to get away from bright colors.
This issue became a problem with Firefox 65 as Mozilla changed something with the bars. This did not happen in Firefox 64. See the attached image link. This is not an issue with the default dark theme it is in ShadowFox. A Simple CSS script may fix this.

https://i.imgur.com/GuZWQ7i.png

**Comment by overdodactyl** [comment]
I'm not entirely sure how that could be - as mentioned above, ShadowFox doesn't touch the tab bar, nor take into account any Windows based colors/themes.  The styling for that is entirely based on Firefox (how they utilize your Windows theme, I am unsure).

Based on your screen shots in https://github.com/SrKomodo/shadowfox-updater/issues/31, however, it doesn't look like you have the FF dark theme in use (the address bar, for example, is white).

Whether Firefox changed something to no longer allow you to use the default theme without a certain Windows config, I am not sure.

If that's the case I may need to look into overriding the tab color, but as it stands it is not ShadowFox causing bright colors in your tab region.

**Comment by overdodactyl** [comment]
@loopy750, any insights here by chance?

**Comment by GTK66** [comment]
I will put this as simple as I can. Beginning with Firefox 65 Firefox uses the color scheme that the user has set in Windows 10. If you have it set to Blue, The Tabs Bar at the top of Firefox will be Blue.
To fix this the Windows 10 user must change his color scheme to a dark shade to get the total dark view in Firefox. This works but it makes Windows 10 look even worse than it does. I corrected my issue by Installing That Black Theme by Madonna. All of the above being said, other users will have the same problem. In Firefox 64 this was not an issue. It is in any release greater than Firefox 64.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by overdodactyl** [comment]
Gotcha.

So generally speaking, in the past I've opted to stay as consistant with Firefox's look as possible, and make ShadowFox simply a complementary feature to the available dark theme rather than res-style/change things that are designed with intention for the dark theme.

I would tend to agree though that having a colored tab area doesn't fit great with ShadowFox, so maybe this is a case worth making an exception for.  

I don't use Windows though, so I'm not sure how this theming fits in with their ecosystem/how users would feel about me overriding it.

I guess another possibility would be to add an option in the updater that could append something to the effect of 

```css
#TabsToolbar {
    background: var(--tone-9) !important;
}
````

to `userChrome.css` (pinging @SrKomodo in case you have any thoughts/opinions on this).

Feedback from other Windows users would be greatly appreciated as well.

Relevant reddit thread with a screenshot of how Firefox is effected:

https://old.reddit.com/r/firefox/comments/9ukhed/nightly_dark_theme_menu_bar_no_longer_dark/

**Comment by loopy750** [comment]
It doesn't look too bad with the light theme, but does look horrible with the dark theme.

```css
/* Dark theme */

.tab-background:not([selected]):-moz-lwtheme-brighttext,
.browser-toolbar.titlebar-color:-moz-lwtheme-brighttext {
  background-color: #0C0C0D !important;
  color: #F9F9FA !important;
}

/* Light theme */

.tab-background:not([selected]):-moz-lwtheme-darktext,
.browser-toolbar.titlebar-color:-moz-lwtheme-darktext {
  background-color: #E3E4E6 !important;
  color: #18191A !important;
}
```
