### ISSUE TITLE
Menus have compact design.

### ISSUE THREAD

**Issue by xAphex** [overdodactyl/ShadowFox#24]
i found this theme from Reddit, and i freaking love it, the only problem i found with it is that the menus (all of them) have compact design, they all seems to be squished together.

### Context Menu: [Before](https://image.prntscr.com/image/UJqZwPzRQ8_tG2IdtoGRAA.png) | [After](https://image.prntscr.com/image/TaMuNdOvTHi3s42Ad3p1hg.png)

Is there something i could change in the CSS files to fix this?

Thank you for creating this awesome theme +1

**Comment by overdodactyl** [comment]
Hi @xAphex, I'm glad you're enjoying the project!

Funny enough, I was just talking to another fellow Redditor about this.  It appears to be a Windows specific problem (and I unfortunately don't have Windows to test on).

Starting on line 61 of `dark_context_menus.css`, you should see this:

```css
/* Increase height between menu items */
menupopup menu, menuitem {
      padding-top: .5px !important;
}
```
If you're using the combined `userChrome.css` file in the main portion of the repo,  this appears near line 257.  

Try changing that to 

```css
menupopup menu,  menuitem {
      padding-top: 5px !important;
      padding-bottom: 5px !important;
}
```
and let me know if that fixes things.

**Comment by overdodactyl** [comment]
Should be fixed - will reopen if not.

**Comment by xAphex** [comment]
yes it fixed it, thank you.
5px turns out to be too much space so i changed it to 4px and it works much better now.

**Comment by overdodactyl** [comment]
No problem - that's now included in the main repo (only applies to windows users), so if you update you won't have to worry about it.

**Comment by CaptaPraelium** [comment]
I thought it was in my head....but I liked it so I didn't say anything. Maybe this could be optional in future?

**Comment by overdodactyl** [comment]
@CaptaPraelium, is it back to looking the "compact" way?

I think I changed it back in ed0b92 because the approach I took didn't actually work as I expected

**Comment by lopardo** [comment]
I get compact menus right now (updated with git) on Manjaro Linux and Windows (both using dark themes/visual styles).

**Comment by overdodactyl** [comment]
Hi @lopardo, for Windows check out issue #60.  If it's a problem for Linux as well I'll try and work on getting a fix included for that

**Comment by CaptaPraelium** [comment]
I just fixed this by accident. I wish I had the compact menus again! LOL

**Comment by overdodactyl** [comment]
I can put a different compact version of userChrome in the repo if you would like.

Other option would be to add something like this to the end of your file:

```css
/* Increase height between menu items */
menupopup menu, menuitem {
      padding-top: .5px !important;
      padding-bottom: .5px !important;
}
```
