### ISSUE TITLE
Themeing dirListing.css

### ISSUE THREAD

**Issue by xAphex** [overdodactyl/ShadowFox#39]
If you go to Firefox and type this as the URL `file:///C:/` it will open explorer in Firefox.

I tried to theme it but failed, i don't know how to make `userChrome.css` and `userContent.css` load this code:

```css
@-moz-document url("chrome://global/skin/dirListing/dirListing.css") {
	:root {
		background-color: var(--primary-dark-color);
		color: var(--dark-accent);
	}

	body {
		border: 1px solid var(--mid-way-color);
		background-color: var(--dark-accent);
		color: var(--light-accent-color);
	}

	h1 {
		border-bottom: 1px solid var(--light-accent-color);
	}

	body > table > tbody > tr:hover {
		outline: 1px solid var(--mid-way-color);
	}
}
```

If you manage to figure out how to do it, that would be awesome.
