### ISSUE TITLE
Meta: Including non-dark theme tweaks, e.g hiding tabs when using treestyle

### ISSUE THREAD

**Issue by krruzic** [overdodactyl/ShadowFox#53]
Loving this theme, had made a similar one but this fixes a lot of my issues. Anyway, was wondering if/how CSS could be used if you're using treestyle tabs that hides the whole tab bar.

I've put together some that does this but no idea how to merge it in without forcing it on people.
```css
/* hide tabs */
#tabbrowser-tabs { visibility: hidden !important; }
tab { display: none !important; }

/* CSS to make urlbar and window controls 1 line */
#nav-bar {      
  margin-bottom: -1px !important;               /* remove navbar bottom 1px border */
  margin-top: -30px !important;
  margin-right: 7.2vw !important; 
  border-top: none !important;
}   

/* Remove padding above tabbar in compact mode */
#main-window[sizemode="normal"] > #titlebar {
  -moz-appearance: initial !important;
}

/* Back & Forward buttons */  
#back-button > .toolbarbutton-icon,
#forward-button > .toolbarbutton-icon {
  transform: scale(0.9, 0.9) !important;
  margin-left: -2px !important;
  margin-right: -2px !important; 
}

/* Move hamburger menu to the left */
#PanelUI-button,
#customization-panel-container,
#customization-panelWrapper .panel-arrow { 
  -moz-box-ordinal-group: 0 !important;
  margin-right: -6px !important;
}

#appMenu-popup {
  margin-right: -258px !important;
}

#appMenu-popup .panel-arrow {
  margin-right: 248px !important;
}

/* More tools... button */
#nav-bar-overflow-button { 
  transform: scale(0.9, 0.9) !important;
}

#titlebar-buttonbox {
  background: var(--chrome-secondary-background-color) !important;
}
```

Ends up looking like this: 
![oneline](https://user-images.githubusercontent.com/4000854/34647413-6499f1bc-f33f-11e7-8074-032b0da81009.PNG)
