### ISSUE TITLE
uMatrix color scheme

### ISSUE THREAD

**Issue by Shourai** [overdodactyl/ShadowFox#82]
Often I have to open the umatrix popup to enable javascript to allow some pages on the web to render properly.
The default color scheme of umatrix is very bright, especially the harsh green and red.
Do you think we should create a more pleasing red/green color scheme?
This could also be applied to ublock for consistency sake.
Currently I have the following colorscheme for umatrix
```css
  .t1 {
    border-color: #debaba !important;
    color: black !important;
    background-color: #ECBDBA !important;
}
  .t2 {
	border-color: #bad6ba !important;
	color: black !important;
	background-color: #C3DeBB !important;
  }
  .t81 {
	color: white !important;
	background-color: #F18E86 !important;
}
  .t82 {
	color: white !important;
	background-color: #8BBA8D !important;
}
```
where the colors are a lot more pale.
![image](https://user-images.githubusercontent.com/10200748/37168004-c9819c08-2303-11e8-8b20-1d46b46b3eba.png)
vs
![image](https://user-images.githubusercontent.com/10200748/37168130-2e8ea5d2-2304-11e8-95bf-098edd9610f1.png)
