### ISSUE TITLE
menu bar and pop menu text size

### ISSUE THREAD

**Issue by tsunami2311** [overdodactyl/ShadowFox#95]
![bugs](https://user-images.githubusercontent.com/12301593/37364156-1e2b8bfe-26d0-11e8-85ae-d78badbc93f8.png)

The menu bar file,edit,view etc and pop menu now have much bigger text size. think this effect FF59 only

I was previously using shadowfox css version from feb 8th with F58 and text size from all those were normal, once FF59 came threw text size fro all that got bigger, is almost like pop up menu has bold effect added now, and text size of drop down menus is now 2 text size bigger. 

IF shadowfox is removed text for all them goes back to normal

![bugs](https://user-images.githubusercontent.com/12301593/37364448-f63abb96-26d0-11e8-85f4-1c8c78f4dd87.png)

**Comment by overdodactyl** [comment]
@loopy750, any ideas with this by chance?

Not noticing any changes here on macOS

**Comment by tsunami2311** [comment]
All I been able to fiqure out is this.

In FF58 Current Shadow fox verisons and feb 8th text size is fine, in FF59 which came threw today current shadowfox verisons and feb 8th I was using both have text size much bigger, as soon as Shadowfox css files are removed the text size goes back to normal, I have already tried new FF profiles it still happens.

I think it has something to do with FF59 but i cant be sure I i not code writer, I just now i noticed this the moment FF59 came threw,

This is on Windows 10 1703 build

**Comment by overdodactyl** [comment]
Just looked at the `@media` statements specific for windows and looks like the font is changed.  FF58 had a bug that prevented the proper usage of `@media`, so you're probably just noticing it now because that bug has been fixed.

@loopy750, what do you think, should we change this back/delete the `font-size` lines?  Got a few messages about this on Reddit as well.

**Comment by overdodactyl** [comment]
> must been around for while but only noticable now cause of FF 59?

Correct.  There's some Window's specific styling in the repo, but there was a Firefox bug that essentially prevented it from going into effect.

I *believe* you could alter this by removing the `font-size` lines here:

https://github.com/overdodactyl/ShadowFox/blob/33a18a079fac1f4c1fd2dcf5ac994b436412254e/userChrome.css#L459-L489

but I don't have Windows to verify that on. If you want to give that a try and let me know, that would be great.

**Comment by tsunami2311** [comment]
removing 459 to 489 fixes the text issue

**Comment by overdodactyl** [comment]
Thanks. I've at least temporarily commented out that section of code until I decide what should be done with it (maybe it's something to go into the More Tweaks wiki page).

**Comment by loopy750** [comment]
I suppose it could go in the tweaks wiki as it's technically not something that helps make the theme dark. The font size matches macOS and doesn't increase the size of the menu/s at all.

But if people aren't liking it, then I totally understand it not being enabled by default.

I personally like it, but I've also modified stuff in the Windows registry such as "FontSubstitutes" , so some of the fonts I see aren't the Windows default.

**Comment by overdodactyl** [comment]
>I've also modified stuff in the Windows registry such as "FontSubstitutes"

**Comment by overdodactyl** [comment]
>I've also modified stuff in the Windows registry such as "FontSubstitutes"

Perhaps that's the difference being seen. I guess it won't be possible to please everyone with visual changes though, so bound to happen that some people like a tweak and others not.

**Comment by overdodactyl** [comment]
@loopy750, on a similar note, I think I'm going to put back the menu separators I removed to give them more of the native feel. 

On macOS, I can change what I currently have to the following:

```css
menupopup menuseparator {
  -moz-appearance: none !important;
  padding: 1px !important;
  margin: 5px 0px!important;
  background: var(--in-content-table-border-dark-color) !important;
}
```

For the section under the `@media` selector, does it look right on Windows if I change it to:



```css
menupopup menuseparator {
   border-color: var(--in-content-table-border-dark-color) !important;
  }
```

?

Here's the look on macOS:


![context](https://user-images.githubusercontent.com/33071129/37415289-02927320-27a3-11e8-8643-895d90fbc127.png)

**Comment by overdodactyl** [comment]
@tsunami2311, the picture shown above *is* the default Firefox text.  Here is a side-by-side comparing default to ShadowFox:

![context_comparison](https://user-images.githubusercontent.com/33071129/37419856-494f4b94-27ad-11e8-917b-90fea883e0b1.png)

Unless I'm missing something, all font changes were removed in 4f9dfd0

**Comment by tsunami2311** [comment]
for MacOS maybe but that is not what defualts look like in Windows

![deaults](https://user-images.githubusercontent.com/12301593/37420289-cba0a5b4-278c-11e8-912a-f45c5029fb05.png)

**Comment by overdodactyl** [comment]
The fonts in your two context menus look identical, so I guess I'm failing to see what the issue with the current font sizes are.

**Comment by tsunami2311** [comment]
are you saying  image I posted pop up menu text looks the same as image of pop up menu text you posted? cause when I look at your image and my image of default text they most definitely not the same kind of text.

The image of pop up/context menu I showing it image of the Text with Shadowfox and with out shadowfox, the text should look the same, What I am saying is defaults of Fonts on Firefox in Windows vs MacOS are different

**Comment by overdodactyl** [comment]
I'm saying the fonts on macOS are the same before and after ShadowFox is applied.  Likewise, based on your screenshot, they are the same before and after on Windows as well.

In other words, ShadowFox isn't currently altering font size on any platform.

**Comment by tsunami2311** [comment]
yah I think put back your padded/separators in to shadowfox build, and leave out font-size changes and I will test cause I think it really was just the font size entry that messed with that. cause separators and padding should have no baring on what text looks like no?

Actual I will see if I can ammend your changes in to my css files which css files do those change go in?

**Comment by overdodactyl** [comment]
To test it, try changing the following lines:

https://github.com/overdodactyl/ShadowFox/blob/4be1d3f5d71520893cfc02ec4676165dfc6f6ad5/userChrome.css#L371-#L374

to 

```css
menupopup menuseparator {
  -moz-appearance: none !important;
  padding: 1px !important;
  margin: 5px 0px!important;
  background: var(--in-content-table-border-dark-color) !important;
}
```

and 
https://github.com/overdodactyl/ShadowFox/blob/4be1d3f5d71520893cfc02ec4676165dfc6f6ad5/userChrome.css#L410-#L413

to 

```css
menupopup menuseparator {
   border-color: var(--in-content-table-border-dark-color) !important;
}
```

**Comment by tsunami2311** [comment]
this is what drop down menu look and context menu looks like now
![padding](https://user-images.githubusercontent.com/12301593/37423365-04828c56-2794-11e8-81c5-0f36b980fa71.png)

**Comment by overdodactyl** [comment]
Agreed.  The line is too thick compared to what you're original screenshot looked like.

Try making the second snippet the following:

```css
menupopup menuseparator {
   padding: 1px !important;
   border-color: var(--in-content-table-border-dark-color) !important;
}
```

**Comment by tsunami2311** [comment]
![padding](https://user-images.githubusercontent.com/12301593/37424036-d305fed6-2795-11e8-90cf-7818087553c0.png)

Not as bad i guess,

**Comment by overdodactyl** [comment]
Looks a little smaller I think? You can keep decreasing the value of `padding: 0.5px !important;` until it looks good (hopefully)

**Comment by tsunami2311** [comment]
I know i have seperaters in the bookmark menu I try some like 0.05px if that works

**Comment by tsunami2311** [comment]
![padding](https://user-images.githubusercontent.com/12301593/37424702-8b003b4a-2797-11e8-96c6-f843006a32a4.png)

I changed bot padding to 0.05px it didnt really make them any smaller, but it does show separators i know my bookmark menu has, I dont really care for separators  being shown on context menu though

**Comment by overdodactyl** [comment]
One last thing to try would be adding `border: 1px solid !important`

**Comment by tsunami2311** [comment]
Where line am I looking to put that on?

As now I have both the padding lines set to 0.02px and look much perfect for the drop down menu not fan of the context seperators though

**Comment by overdodactyl** [comment]
Make it this:

```css
menupopup menuseparator {
   padding: 0.5px !important;
   border-color: var(--in-content-table-border-dark-color) !important;
   border: 1px solid !important
}
```
